name: Lint
on: [push, pull_request, workflow_dispatch]
jobs:
  hlint:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/hlint-scan@v1
