name: Run tests
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - '8.0'
          - '8.2'
          - '8.4'
          - '8.6'
          - '8.8'
          - '8.10'
          - '9.0'
          - '9.2'
          - '9.4'
          - '9.6'
          - '9.8'
          - '9.10'
          - '9.12'
          - latest-nightly
        os: [ubuntu-latest]
    name: ${{ matrix.os }} / GHC ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          ghcup-release-channel: https://ghc.gitlab.haskell.org/ghcup-metadata/ghcup-nightlies-0.0.7.yaml
      - name: Test
        run: cabal test --test-options='+RTS -N -RTS --quickcheck-tests 1000 --quickcheck-max-size 120'
