name: Run tests
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - version: latest-nightly
            cabal-args: --allow-newer
          - version: '9.12'
          - version: '9.10'
          - version: '9.8'
          - version: '9.6'
          - version: '9.4'
          - version: '9.2'
          - version: '9.0'
          - version: '8.10'
          - version: '8.8'
          - version: '8.6'
          - version: '8.4'
          - version: '8.2'
          - version: '8.0'
    name: GHC ${{ matrix.ghc.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc.version }}
          ghcup-release-channel: https://ghc.gitlab.haskell.org/ghcup-metadata/ghcup-nightlies-0.0.7.yaml
      - name: Test
        run: cabal test --test-options='+RTS -N -RTS --quickcheck-tests 1000 --quickcheck-max-size 120' ${{ matrix.ghc.cabal-args }}
