name: Run tests
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc:
          - 8.4.4
          - 8.6.5
          - 8.8.4
          - 8.10.7
          - 9.0.2
          - 9.2.8
          - 9.4.8
          - 9.6.6
          - 9.8.4
          - 9.10.1
          - 9.12.1
        cabal: ['3.14.1.1']
        os: [ubuntu-latest]
    name: ${{ matrix.os }} / GHC ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Test
        run: cabal test --test-options='+RTS -N -RTS --quickcheck-tests 1000 --quickcheck-max-size 120'
